//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiloRobot.RemoteControl.UserInterface {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiloRobot.RemoteControl.UserInterface.UserMessages", typeof(UserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed due to authentication error. Please try again..
        /// </summary>
        internal static string CONNECTION_AUTHENTICATION_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("CONNECTION_AUTHENTICATION_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid inputs.
        /// </summary>
        internal static string CONNECTION_EMPTY_VALUES_HEADER {
            get {
                return ResourceManager.GetString("CONNECTION_EMPTY_VALUES_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the IP Address, Username and Password..
        /// </summary>
        internal static string CONNECTION_EMPTY_VALUES_MESSAGE {
            get {
                return ResourceManager.GetString("CONNECTION_EMPTY_VALUES_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        internal static string CONNECTION_ERROR_HEADER {
            get {
                return ResourceManager.GetString("CONNECTION_ERROR_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed..
        /// </summary>
        internal static string CONNECTION_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("CONNECTION_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..
        /// </summary>
        internal static string CONNECTION_SOCKET_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("CONNECTION_SOCKET_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection falied..
        /// </summary>
        internal static string CONNECTION_SSHCONNECTION_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("CONNECTION_SSHCONNECTION_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection successful.
        /// </summary>
        internal static string CONNECTION_SUCCESSFUL_HEADER {
            get {
                return ResourceManager.GetString("CONNECTION_SUCCESSFUL_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now connected to:.
        /// </summary>
        internal static string CONNECTION_SUCCESSFUL_MESSAGE {
            get {
                return ResourceManager.GetString("CONNECTION_SUCCESSFUL_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnection error.
        /// </summary>
        internal static string DISCONNECTION_ERROR_HEADER {
            get {
                return ResourceManager.GetString("DISCONNECTION_ERROR_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnection failed..
        /// </summary>
        internal static string DISCONNECTION_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("DISCONNECTION_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnection failed because connection has been disposed..
        /// </summary>
        internal static string DISCONNECTION_OBJECT_DISPOSED_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("DISCONNECTION_OBJECT_DISPOSED_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnection successful.
        /// </summary>
        internal static string DISCONNECTION_SUCCESSFUL_HEADER {
            get {
                return ResourceManager.GetString("DISCONNECTION_SUCCESSFUL_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnection has been successful..
        /// </summary>
        internal static string DISCONNECTION_SUCCESSFUL_MESSAGE {
            get {
                return ResourceManager.GetString("DISCONNECTION_SUCCESSFUL_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging failed.
        /// </summary>
        internal static string LOGGING_ERROR_HEADER {
            get {
                return ResourceManager.GetString("LOGGING_ERROR_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in logging messages. Please restart the application..
        /// </summary>
        internal static string LOGGING_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("LOGGING_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection.
        /// </summary>
        internal static string NO_CONNECTION_HEADER {
            get {
                return ResourceManager.GetString("NO_CONNECTION_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not connected to the Milo..
        /// </summary>
        internal static string NO_CONNECTION_MESSAGE {
            get {
                return ResourceManager.GetString("NO_CONNECTION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send command error.
        /// </summary>
        internal static string RUN_COMMAND_ERROR_HEADER {
            get {
                return ResourceManager.GetString("RUN_COMMAND_ERROR_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while sending command to Milo..
        /// </summary>
        internal static string RUN_COMMAND_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("RUN_COMMAND_ERROR_MESSAGE", resourceCulture);
            }
        }
    }
}
