//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputResource
    {
        public int ID { get; set; }
        public string ProcessorType { get; set; }
        public string Flash { get; set; }
        public string RAM { get; set; }
        public string EEPROM { get; set; }
        public string Frequency { get; set; }
        public int NumberOfChips { get; set; }
    }
}
